/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */
package com.solteq.liferay.site.initializer.audit.model.impl;

import com.solteq.liferay.site.initializer.audit.model.SIAuditEntry;
import com.solteq.liferay.site.initializer.audit.service.SIAuditEntryLocalServiceUtil;

/**
 * The extended model base implementation for the SIAuditEntry service. Represents a row in the &quot;sq_SIAuditEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SIAuditEntryImpl}.
 * </p>
 *
 * @author Solteq
 * @see SIAuditEntryImpl
 * @see SIAuditEntry
 * @generated
 */
public abstract class SIAuditEntryBaseImpl extends SIAuditEntryModelImpl implements SIAuditEntry {

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a si audit entry model instance should use the <code>SIAuditEntry</code> interface instead.
     */
    @Override
    public void persist() {
        if (this.isNew()) {
            SIAuditEntryLocalServiceUtil.addSIAuditEntry(this);
        } else {
            SIAuditEntryLocalServiceUtil.updateSIAuditEntry(this);
        }
    }
}
