/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */
package com.solteq.liferay.site.initializer.audit.model;

import java.util.Date;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SIAuditEntry service. Represents a row in the &quot;sq_SIAuditEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.solteq.liferay.site.initializer.audit.model.impl.SIAuditEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.solteq.liferay.site.initializer.audit.model.impl.SIAuditEntryImpl</code>.
 * </p>
 *
 * @author Solteq
 * @see SIAuditEntry
 * @generated
 */
@ProviderType
public interface SIAuditEntryModel extends BaseModel<SIAuditEntry>, ShardedModel {

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a si audit entry model instance should use the {@link SIAuditEntry} interface instead.
     */

    /**
     * Returns the primary key of this si audit entry.
     *
     * @return the primary key of this si audit entry
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this si audit entry.
     *
     * @param primaryKey the primary key of this si audit entry
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the si audit entry ID of this si audit entry.
     *
     * @return the si audit entry ID of this si audit entry
     */
    public long getSiAuditEntryId();

    /**
     * Sets the si audit entry ID of this si audit entry.
     *
     * @param siAuditEntryId the si audit entry ID of this si audit entry
     */
    public void setSiAuditEntryId(long siAuditEntryId);

    /**
     * Returns the group ID of this si audit entry.
     *
     * @return the group ID of this si audit entry
     */
    public long getGroupId();

    /**
     * Sets the group ID of this si audit entry.
     *
     * @param groupId the group ID of this si audit entry
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this si audit entry.
     *
     * @return the company ID of this si audit entry
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this si audit entry.
     *
     * @param companyId the company ID of this si audit entry
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this si audit entry.
     *
     * @return the user ID of this si audit entry
     */
    public long getUserId();

    /**
     * Sets the user ID of this si audit entry.
     *
     * @param userId the user ID of this si audit entry
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this si audit entry.
     *
     * @return the user uuid of this si audit entry
     */
    public String getUserUuid();

    /**
     * Sets the user uuid of this si audit entry.
     *
     * @param userUuid the user uuid of this si audit entry
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this si audit entry.
     *
     * @return the create date of this si audit entry
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this si audit entry.
     *
     * @param createDate the create date of this si audit entry
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the si key of this si audit entry.
     *
     * @return the si key of this si audit entry
     */
    @AutoEscape
    public String getSiKey();

    /**
     * Sets the si key of this si audit entry.
     *
     * @param siKey the si key of this si audit entry
     */
    public void setSiKey(String siKey);

    /**
     * Returns the processing time of this si audit entry.
     *
     * @return the processing time of this si audit entry
     */
    public long getProcessingTime();

    /**
     * Sets the processing time of this si audit entry.
     *
     * @param processingTime the processing time of this si audit entry
     */
    public void setProcessingTime(long processingTime);

    /**
     * Returns the status of this si audit entry.
     *
     * @return the status of this si audit entry
     */
    public int getStatus();

    /**
     * Sets the status of this si audit entry.
     *
     * @param status the status of this si audit entry
     */
    public void setStatus(int status);

    /**
     * Returns the message of this si audit entry.
     *
     * @return the message of this si audit entry
     */
    @AutoEscape
    public String getMessage();

    /**
     * Sets the message of this si audit entry.
     *
     * @param message the message of this si audit entry
     */
    public void setMessage(String message);

    @Override
    public SIAuditEntry cloneWithOriginalValues();

    public default String toXmlString() {
        return null;
    }
}
